using Transiever.SieveRuler.Models;

namespace Transiever.SieveRuler.Cli;

public static class RuleInspector
{
    public static void Print(IReadOnlyCollection<RuleDefinition> rules, string sourceFile)
    {
        Console.WriteLine($"Rules file: {sourceFile}");
        Console.WriteLine($"Rules: {rules.Count}");
        Console.WriteLine();

        if (rules.Count == 0)
        {
            Console.WriteLine("No rules found.");
            return;
        }

        PrintSummary(rules);
        Console.WriteLine();

        var index = 1;

        foreach (RuleDefinition rule in rules)
        {
            PrintRule(index, rule);
            index++;
        }

        PrintWarnings(rules);
    }

    private static void PrintSummary(IReadOnlyCollection<RuleDefinition> rules)
    {
        int folders = rules
            .Select(rule => rule.TargetFolder)
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Count();

        int conditionCount = rules.Sum(rule => rule.Conditions.Count);

        Console.WriteLine("Summary:");
        Console.WriteLine($"  Target folders: {folders}");
        Console.WriteLine($"  Conditions: {conditionCount}");

        foreach (IGrouping<RuleConditionType, RuleCondition> group in rules
            .SelectMany(rule => rule.Conditions)
            .GroupBy(condition => condition.Type)
            .OrderBy(group => group.Key.ToString()))
        {
            Console.WriteLine($"    {group.Key}: {group.Count()}");
        }
    }

    private static void PrintRule(int index, RuleDefinition rule)
    {
        string name = string.IsNullOrWhiteSpace(rule.Name)
            ? "<unnamed rule>"
            : rule.Name;

        Console.WriteLine($"[{index:000}] {name}");
        Console.WriteLine($"  Folder: {DisplayValue(rule.TargetFolder)}");
        Console.WriteLine($"  Mode: {rule.ConditionMode}");

        if (rule.Conditions.Count == 0)
        {
            Console.WriteLine("  Conditions: <none>");
            Console.WriteLine();
            return;
        }

        Console.WriteLine("  Conditions:");

        foreach (RuleCondition condition in rule.Conditions)
        {
            string[] values = condition.GetValues()
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .ToArray();

            if (values.Length == 0)
            {
                Console.WriteLine($"    - {condition.Type}: <empty>");
                continue;
            }

            Console.WriteLine($"    - {condition.Type}: {string.Join(" | ", values)}");
        }

        Console.WriteLine();
    }

    private static void PrintWarnings(IReadOnlyCollection<RuleDefinition> rules)
    {
        var warnings = new List<string>();

        var index = 1;

        foreach (RuleDefinition rule in rules)
        {
            string prefix = $"Rule {index:000}";

            if (string.IsNullOrWhiteSpace(rule.Name))
            {
                warnings.Add($"{prefix}: missing rule name.");
            }

            if (string.IsNullOrWhiteSpace(rule.TargetFolder))
            {
                warnings.Add($"{prefix}: missing target folder.");
            }

            if (rule.Conditions.Count == 0)
            {
                warnings.Add($"{prefix}: no conditions.");
            }
            else if (rule.Conditions.All(condition => condition.GetValues().Count == 0))
            {
                warnings.Add($"{prefix}: all conditions are empty.");
            }

            index++;
        }

        if (warnings.Count == 0)
        {
            return;
        }

        Console.WriteLine("Warnings:");

        foreach (string warning in warnings)
        {
            Console.WriteLine($"  - {warning}");
        }

        if (warnings.Count == rules.Count)
        {
            Console.WriteLine();
            Console.WriteLine("Every rule looks empty. Check whether the JSON file was generated by the current Transiever.SieveRuler version.");
        }
    }

    private static string DisplayValue(string value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? "<missing>"
            : value;
    }
}
