
using Transiever.SieveRuler.Models;
using System.Text;

namespace Transiever.SieveRuler.Services;

public sealed class SieveGenerator : ISieveGenerator
{
    public string Generate(
        IEnumerable<RuleDefinition> rules,
        string sourceFile = "rules.json")
    {
        List<RuleDefinition> sourceRules = rules.ToList();
        string body = GenerateRuleBody(sourceRules);
        IReadOnlyCollection<string> capabilities =
            GetRequiredCapabilities(sourceRules);

        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Transiever.SieveRuler.");
        sb.AppendLine("# Review before installing on a Sieve-compatible mail server.");
        sb.AppendLine($"# Source: {SieveStringEscaper.EscapeComment(sourceFile)}");
        sb.AppendLine();
        sb.AppendLine($"require {RenderStringList(capabilities)};");
        sb.AppendLine();
        sb.Append(body);

        return sb.ToString();
    }

    public string GenerateRuleBody(IEnumerable<RuleDefinition> rules)
    {
        List<SieveRuleBlock> ruleBlocks = rules
            .Select(RenderRule)
            .Where(block => block is not null)
            .Cast<SieveRuleBlock>()
            .ToList();

        var sb = new StringBuilder();
        foreach (SieveRuleBlock block in ruleBlocks)
            sb.Append(block.Text);

        return sb.ToString();
    }

    public IReadOnlyCollection<string> GetRequiredCapabilities(
        IEnumerable<RuleDefinition> rules)
    {
        List<SieveRuleBlock> ruleBlocks = rules
            .Select(RenderRule)
            .Where(block => block is not null)
            .Cast<SieveRuleBlock>()
            .ToList();

        var capabilities = new SortedSet<string>(StringComparer.Ordinal)
        {
            "fileinto"
        };

        foreach (string capability in ruleBlocks.SelectMany(block => block.RequiredCapabilities))
            capabilities.Add(capability);

        return capabilities;
    }

    private static SieveRuleBlock? RenderRule(RuleDefinition rule)
    {
        if (string.IsNullOrWhiteSpace(rule.TargetFolder))
            return null;

        var conditions = rule.Conditions
            .Select(RenderCondition)
            .Where(condition => condition is not null)
            .Cast<SieveCondition>()
            .ToList();

        if (conditions.Count == 0)
            return null;

        var sb = new StringBuilder();

        sb.AppendLine(SieveProviderMetadata.RenderFlag(rule, DateTimeOffset.UtcNow));

        if (conditions.Count == 1)
        {
            sb.AppendLine($"if {conditions[0].Test}");
        }
        else
        {
            var combinator = rule.ConditionMode == RuleConditionMode.Any
                ? "anyof"
                : "allof";

            sb.AppendLine(
                $"if {combinator} ( {string.Join(" , ", conditions.Select(condition => condition.Test))} )");
        }

        sb.AppendLine("{");
        sb.AppendLine($"fileinto \"{SieveStringEscaper.Escape(rule.TargetFolder)}\" ;");
        sb.AppendLine("}");
        sb.AppendLine();

        return new SieveRuleBlock(
            sb.ToString(),
            conditions.SelectMany(condition => condition.RequiredCapabilities).ToArray());
    }

    private static SieveCondition? RenderCondition(RuleCondition condition)
    {
        var values = condition.GetValues()
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (values.Length == 0)
            return null;

        return condition.Type switch
        {
            RuleConditionType.SenderContains => new SieveCondition(
                $"address :contains \"from\" {RenderStringOrList(values)}"),

            RuleConditionType.ReceiverContains => new SieveCondition(
                $"address :contains [\"to\", \"cc\"] {RenderStringOrList(values)}"),

            RuleConditionType.SubjectContains => new SieveCondition(
                $"header :contains \"subject\" {RenderStringOrList(values)}"),

            RuleConditionType.BodyContains => new SieveCondition(
                $"body :contains {RenderStringOrList(values)}",
                ["body"]),

            RuleConditionType.SubjectOrBodyContains => new SieveCondition(
                $"anyof ( header :contains \"subject\" {RenderStringOrList(values)} , body :contains {RenderStringOrList(values)} )",
                ["body"]),

            _ => null
        };
    }

    private static string RenderStringOrList(IReadOnlyCollection<string> values)
    {
        return values.Count == 1
            ? $"\"{SieveStringEscaper.Escape(values.Single())}\""
            : RenderStringList(values);
    }

    private static string RenderStringList(IEnumerable<string> values)
    {
        return $"[{string.Join(", ", values.Select(value => $"\"{SieveStringEscaper.Escape(value)}\""))}]";
    }

    private sealed record SieveCondition(
        string Test,
        IReadOnlyCollection<string> RequiredCapabilities)
    {
        public SieveCondition(string test)
            : this(test, [])
        {
        }
    }

    private sealed record SieveRuleBlock(
        string Text,
        IReadOnlyCollection<string> RequiredCapabilities);
}
