using Transiever.SieveRuler.Models;
using System.Text;

namespace Transiever.SieveRuler.Services;

/// <summary>
/// Generates Sieve from reconciled rule definitions.
/// </summary>
public sealed class SieveGenerator : ISieveGenerator
{
    public string Generate(
        IEnumerable<RuleDefinition> rules,
        string sourceFile = "rules.json")
    {
        List<RuleDefinition> sourceRules = rules.ToList();
        string body = GenerateRuleBody(sourceRules);
        IReadOnlyCollection<string> capabilities =
            GetRequiredCapabilities(sourceRules);

        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Transiever.SieveRuler.");
        sb.AppendLine("# Review before installing on a Sieve-compatible mail server.");
        sb.AppendLine($"# Source: {SieveStringEscaper.EscapeComment(sourceFile)}");
        sb.AppendLine();
        if (capabilities.Count > 0)
        {
            sb.AppendLine($"require {RenderStringList(capabilities)};");
            sb.AppendLine();
        }

        sb.Append(body);

        return sb.ToString();
    }

    public string GenerateRuleBody(IEnumerable<RuleDefinition> rules)
    {
        List<SieveRuleBlock> ruleBlocks = rules
            .Select(RenderRule)
            .Where(block => block is not null)
            .Cast<SieveRuleBlock>()
            .ToList();

        var sb = new StringBuilder();
        foreach (SieveRuleBlock block in ruleBlocks)
            sb.Append(block.Text);

        return sb.ToString();
    }

    public IReadOnlyCollection<string> GetRequiredCapabilities(
        IEnumerable<RuleDefinition> rules)
    {
        List<SieveRuleBlock> ruleBlocks = rules
            .Select(RenderRule)
            .Where(block => block is not null)
            .Cast<SieveRuleBlock>()
            .ToList();

        var capabilities = new SortedSet<string>(StringComparer.Ordinal);

        foreach (string capability in ruleBlocks.SelectMany(block => block.RequiredCapabilities))
            capabilities.Add(capability);

        return capabilities;
    }

    private static SieveRuleBlock? RenderRule(RuleDefinition rule)
    {
        SieveCondition? conditions = RenderConditionGroup(
            rule.Conditions,
            rule.ConditionMode);
        if (conditions is null)
            return null;

        SieveCondition? exceptions = RenderExceptions(rule.Exceptions);
        SieveCondition test = exceptions is null
            ? conditions
            : new SieveCondition(
                $"allof ( {conditions.Test} , {exceptions.Test} )",
                [.. conditions.RequiredCapabilities, .. exceptions.RequiredCapabilities]);

        List<SieveAction> actions = GetEffectiveActions(rule)
            .SelectMany(RenderAction)
            .ToList();
        if (actions.Count == 0)
            return null;

        var sb = new StringBuilder();

        sb.AppendLine(SieveProviderMetadata.RenderFlag(rule));
        sb.AppendLine($"if {test.Test}");
        sb.AppendLine("{");
        foreach (SieveAction action in actions)
            sb.AppendLine(action.Command);

        sb.AppendLine("}");
        sb.AppendLine();

        return new SieveRuleBlock(
            sb.ToString(),
            [
                .. test.RequiredCapabilities,
                .. actions.SelectMany(action => action.RequiredCapabilities)
            ]);
    }

    private static SieveCondition? RenderConditionGroup(
        IReadOnlyList<RuleCondition> sourceConditions,
        RuleConditionMode mode)
    {
        var conditions = sourceConditions
            .Select(RenderCondition)
            .Where(condition => condition is not null)
            .Cast<SieveCondition>()
            .ToList();

        if (conditions.Count == 0)
            return null;

        if (conditions.Count == 1)
            return conditions[0];

        string combinator = mode == RuleConditionMode.Any
            ? "anyof"
            : "allof";
        return new SieveCondition(
            $"{combinator} ( {string.Join(" , ", conditions.Select(condition => condition.Test))} )",
            conditions.SelectMany(condition => condition.RequiredCapabilities).ToArray());
    }

    private static SieveCondition? RenderExceptions(
        IReadOnlyList<RuleCondition> sourceExceptions)
    {
        var exceptions = sourceExceptions
            .Select(RenderCondition)
            .Where(condition => condition is not null)
            .Cast<SieveCondition>()
            .ToList();

        if (exceptions.Count == 0)
            return null;

        string test = exceptions.Count == 1
            ? $"not {exceptions[0].Test}"
            : $"not anyof ( {string.Join(" , ", exceptions.Select(condition => condition.Test))} )";
        return new SieveCondition(
            test,
            exceptions.SelectMany(condition => condition.RequiredCapabilities).ToArray());
    }

    private static SieveCondition? RenderCondition(RuleCondition condition)
    {
        if (condition.Type == RuleConditionType.HasAttachment)
        {
            return new SieveCondition(
                "header :mime :anychild :contains \"Content-Disposition\" \"attachment\"",
                ["mime"]);
        }

        var values = condition.Values
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (values.Length == 0)
            return null;

        return condition.Type switch
        {
            RuleConditionType.SenderContains => new SieveCondition(
                $"address :contains \"from\" {RenderStringOrList(values)}"),

            RuleConditionType.ReceiverContains => new SieveCondition(
                $"address :contains [\"to\", \"cc\"] {RenderStringOrList(values)}"),

            RuleConditionType.SubjectContains => new SieveCondition(
                $"header :contains \"Subject\" {RenderStringOrList(values)}"),

            RuleConditionType.BodyContains => new SieveCondition(
                $"body :contains {RenderStringOrList(values)}",
                ["body"]),

            RuleConditionType.SubjectOrBodyContains => new SieveCondition(
                $"anyof ( header :contains \"Subject\" {RenderStringOrList(values)} , body :contains {RenderStringOrList(values)} )",
                ["body"]),

            _ => null
        };
    }

    private static IReadOnlyList<RuleAction> GetEffectiveActions(RuleDefinition rule)
    {
        if (rule.Actions.Count > 0)
            return rule.Actions;

        return string.IsNullOrWhiteSpace(rule.TargetFolder)
            ? []
            :
            [
                new RuleAction
                {
                    Type = RuleActionType.FileInto,
                    Values = [rule.TargetFolder]
                }
            ];
    }

    private static IEnumerable<SieveAction> RenderAction(RuleAction action)
    {
        string[] values = action.Values
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        switch (action.Type)
        {
            case RuleActionType.FileInto:
                foreach (string value in values)
                {
                    yield return new SieveAction(
                        $"fileinto \"{SieveStringEscaper.Escape(value)}\" ;",
                        ["fileinto"]);
                }

                yield break;
            case RuleActionType.CopyInto:
                foreach (string value in values)
                {
                    yield return new SieveAction(
                        $"fileinto :copy \"{SieveStringEscaper.Escape(value)}\" ;",
                        ["copy", "fileinto"]);
                }

                yield break;
            case RuleActionType.Redirect:
                foreach (string value in values)
                {
                    yield return new SieveAction(
                        $"redirect \"{SieveStringEscaper.Escape(value)}\" ;");
                }

                yield break;
            case RuleActionType.SetFlags:
                if (values.Length > 0)
                {
                    yield return new SieveAction(
                        $"addflag {RenderStringOrList(values)} ;",
                        ["imap4flags"]);
                }

                yield break;
            case RuleActionType.Stop:
                yield return new SieveAction("stop ;");
                yield break;
        }
    }

    private static string RenderStringOrList(IReadOnlyCollection<string> values)
    {
        return values.Count == 1
            ? $"\"{SieveStringEscaper.Escape(values.Single())}\""
            : RenderStringList(values);
    }

    private static string RenderStringList(IEnumerable<string> values)
    {
        return $"[{string.Join(", ", values.Select(value => $"\"{SieveStringEscaper.Escape(value)}\""))}]";
    }

    private sealed record SieveCondition(
        string Test,
        IReadOnlyCollection<string> RequiredCapabilities)
    {
        public SieveCondition(string test)
            : this(test, [])
        {
        }
    }

    private sealed record SieveAction(
        string Command,
        IReadOnlyCollection<string> RequiredCapabilities)
    {
        public SieveAction(string command)
            : this(command, [])
        {
        }
    }

    private sealed record SieveRuleBlock(
        string Text,
        IReadOnlyCollection<string> RequiredCapabilities);
}
