# Generated by Transiever.SieveRuler.
# Review before installing on a Sieve-compatible mail server.
# Source: SIV-002.rules.json

require ["body", "fileinto", "imap4flags"];

## Flag: |UniqueId:682002226|Rulename: Optimized: INBOX/Projects / SenderContains
if allof ( address :contains "from" ["first@example.test", "second@example.test"] , not body :contains "internal" )
{
addflag "\\Seen" ;
fileinto "INBOX/Projects" ;
stop ;
}
