# Generated by Transiever.SieveRuler.
# Review before installing on a Sieve-compatible mail server.
# Source: OUT-001.rules.json

require ["body", "copy", "fileinto", "imap4flags", "mime"];

## Flag: |UniqueId:140970435|Rulename: Project invoices
if allof ( allof ( header :contains "Subject" "invoice" , address :contains "from" "billing@example.test" , address :contains ["to", "cc"] "team@example.test" , header :mime :anychild :contains "Content-Disposition" "attachment" ) , not body :contains "internal" )
{
addflag "\\Seen" ;
fileinto "INBOX/Projects" ;
fileinto :copy "Archive/Projects" ;
redirect "archive@example.test" ;
stop ;
}

